name: 'base setup'

inputs:
  ssh-key:
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup SSH key
      shell: bash
      env:
        SSH_KEY: ${{ inputs.ssh-key }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
