//! Embedded mode support for running Hegel as a library.
//!
//! In embedded mode, the test binary creates a Unix socket server,
//! spawns the `hegel` CLI as a subprocess, and runs tests with
//! data generated by Hegel.
//!
//! # Example
//!
//! ```no_run
//! use hegel::{embedded, gen::{self, Generate}, note};
//!
//! fn main() {
//!     embedded::hegel(|| {
//!         let x = gen::integers::<i32>().generate();
//!         let y = gen::integers::<i32>().generate();
//!         note(&format!("Testing {} + {}", x, y));
//!         assert_eq!(x + y, y + x);
//!     });
//! }
//! ```

use crate::gen::{clear_embedded_connection, set_embedded_connection, set_is_last_run, set_mode};
use crate::HegelMode;
use serde_json::{json, Value};
use std::io::{BufRead, BufReader, Write};
use std::os::unix::net::{UnixListener, UnixStream};
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::process::{Command, ExitStatus, Stdio};
use std::sync::Arc;
use std::time::Duration;
use tempfile::TempDir;

/// Path to the hegel binary, determined at compile time by build.rs.
/// This will be either a system hegel found on PATH, or one installed
/// into the build directory's cache.
const HEGEL_BINARY_PATH: &str = env!("HEGEL_BINARY_PATH");

/// Options for embedded mode execution.
#[derive(Debug, Clone, Default)]
pub struct HegelOptions {
    /// Number of test cases to run. Default: 100.
    pub test_cases: Option<u64>,
    /// Enable debug output from hegel.
    pub debug: bool,
    /// Path to the hegel binary. Default: auto-detected at compile time.
    pub hegel_path: Option<String>,
}

impl HegelOptions {
    /// Create new options with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the number of test cases.
    pub fn with_test_cases(mut self, n: u64) -> Self {
        self.test_cases = Some(n);
        self
    }

    /// Enable debug output.
    pub fn with_debug(mut self) -> Self {
        self.debug = true;
        self
    }

    /// Set the path to the hegel binary.
    pub fn with_hegel_path(mut self, path: impl Into<String>) -> Self {
        self.hegel_path = Some(path.into());
        self
    }
}

/// Special marker used to identify assume(false) panics.
const REJECT_MARKER: &str = "HEGEL_REJECT";

/// Run property-based tests using Hegel in embedded mode with default options.
///
/// This is a convenience wrapper around [`hegel_with_options`] that uses
/// [`HegelOptions::default()`].
///
/// # Example
///
/// ```no_run
/// use hegel::{embedded, gen::{self, Generate}};
///
/// embedded::hegel(|| {
///     let n = gen::integers::<i32>().generate();
///     assert!(n + 0 == n); // Identity property
/// });
/// ```
pub fn hegel<F>(test_fn: F)
where
    F: Fn() + Send + Sync + 'static,
{
    hegel_with_options(test_fn, HegelOptions::default());
}

/// Run property-based tests using Hegel in embedded mode.
///
/// This function:
/// 1. Creates a Unix socket server
/// 2. Spawns the hegel CLI as a subprocess
/// 3. Accepts connections from hegel (one per test case)
/// 4. Runs the test function for each test case
/// 5. Reports results back to hegel
/// 6. Panics if any test case fails
///
/// # Arguments
///
/// * `test_fn` - The test function to run. Should use generators from `hegel::gen`.
/// * `options` - Configuration options for the test run.
///
/// # Panics
///
/// Panics if:
/// - Failed to create socket or spawn hegel
/// - Any test case fails (after shrinking)
/// - Socket communication errors
///
/// # Example
///
/// ```no_run
/// use hegel::{embedded, gen::{self, Generate}};
///
/// embedded::hegel_with_options(|| {
///     let n = gen::integers::<i32>().generate();
///     assert!(n + 0 == n); // Identity property
/// }, embedded::HegelOptions::new().with_test_cases(500));
/// ```
pub fn hegel_with_options<F>(test_fn: F, options: HegelOptions)
where
    F: Fn() + Send + Sync + 'static,
{
    // Create temp directory with socket
    let temp_dir = TempDir::new().expect("Failed to create temp directory");
    let socket_path = temp_dir.path().join("hegel.sock");

    // Create Unix socket server
    let listener = UnixListener::bind(&socket_path).expect("Failed to bind socket");

    // Set non-blocking so we can check if hegel exited
    listener
        .set_nonblocking(true)
        .expect("Failed to set non-blocking");

    // Build hegel command
    let hegel_path = options.hegel_path.as_deref().unwrap_or(HEGEL_BINARY_PATH);
    let mut cmd = Command::new(hegel_path);
    cmd.arg("--client-mode")
        .arg(&socket_path)
        .arg("--no-tui");

    if let Some(n) = options.test_cases {
        cmd.arg("--test-cases").arg(n.to_string());
    }
    if options.debug {
        cmd.arg("--debug");
    }

    cmd.stdout(Stdio::inherit()).stderr(Stdio::inherit());

    // Spawn hegel
    let mut child = cmd.spawn().expect("Failed to spawn hegel");

    // Accept connections until hegel exits
    let test_fn = Arc::new(test_fn);

    loop {
        // Try to accept a connection
        match listener.accept() {
            Ok((stream, _)) => {
                handle_connection(stream, test_fn.clone(), options.debug);
            }
            Err(e) if e.kind() == std::io::ErrorKind::WouldBlock => {
                // No connection ready, check if hegel exited
                match child.try_wait() {
                    Ok(Some(status)) => {
                        handle_exit(status);
                        break;
                    }
                    Ok(None) => {
                        // Hegel still running, wait a bit
                        std::thread::sleep(Duration::from_millis(10));
                    }
                    Err(e) => panic!("Error waiting for hegel: {}", e),
                }
            }
            Err(e) => panic!("Accept failed: {}", e),
        }
    }
}

/// Handle the final exit status from hegel.
fn handle_exit(status: ExitStatus) {
    if !status.success() {
        // Hegel found a failure
        if let Some(code) = status.code() {
            panic!("Hegel test failed (exit code {})", code);
        } else {
            panic!("Hegel terminated by signal");
        }
    }
}

/// Handle a single connection from hegel (one test case).
fn handle_connection<F: Fn()>(stream: UnixStream, test_fn: Arc<F>, debug: bool) {
    // Stream accepted from non-blocking listener may inherit non-blocking mode on macOS.
    // Set it back to blocking for reliable reads.
    stream
        .set_nonblocking(false)
        .expect("Failed to set stream to blocking mode");

    let mut reader = BufReader::new(stream.try_clone().unwrap());
    let mut writer = stream.try_clone().unwrap();

    // Read handshake
    let mut line = String::new();
    if reader.read_line(&mut line).is_err() {
        return; // Connection closed
    }

    let handshake: Value = match serde_json::from_str(&line) {
        Ok(v) => v,
        Err(_) => return, // Invalid handshake
    };

    let is_last = handshake
        .get("is_last_run")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);

    if debug {
        eprintln!("Handshake received: is_last_run={}", is_last);
    }

    // Set thread-local state
    set_mode(HegelMode::Embedded);
    set_is_last_run(is_last);
    set_embedded_connection(stream);

    // Send handshake_ack
    let ack = json!({"type": "handshake_ack"});
    if writeln!(writer, "{}", ack).is_err() {
        clear_embedded_connection();
        set_mode(HegelMode::Standalone);
        return;
    }
    let _ = writer.flush();

    // Run test in catch_unwind
    let result = catch_unwind(AssertUnwindSafe(|| test_fn()));

    // Clear connection before sending result (test is done generating)
    clear_embedded_connection();

    // Send test result
    let result_msg = match result {
        Ok(()) => json!({"type": "test_result", "result": "pass"}),
        Err(e) => {
            // Check if this is an assume(false) panic
            let msg = panic_message(&e);
            if msg == REJECT_MARKER {
                json!({
                    "type": "test_result",
                    "result": "reject"
                })
            } else {
                json!({
                    "type": "test_result",
                    "result": "fail",
                    "message": msg
                })
            }
        }
    };

    if debug {
        eprintln!("Sending result: {}", result_msg);
    }

    let _ = writeln!(writer, "{}", result_msg);
    let _ = writer.flush();

    // Reset mode
    set_mode(HegelMode::Standalone);
}

/// Extract a message from a panic payload.
fn panic_message(payload: &Box<dyn std::any::Any + Send>) -> String {
    if let Some(s) = payload.downcast_ref::<&str>() {
        s.to_string()
    } else if let Some(s) = payload.downcast_ref::<String>() {
        s.clone()
    } else {
        "Unknown panic".to_string()
    }
}
