name: Bump hegel-core

on:
  repository_dispatch:
    types: [hegel-core-release]

permissions: {}

jobs:
  bump:
    name: bump hegel-core
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        id: app-token
        with:
          app-id: ${{ vars.HEGEL_RELEASE_APP_ID }}
          private-key: ${{ secrets.HEGEL_RELEASE_APP_PRIVATE_KEY }}
          repositories: hegel-rust

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27

      - name: Bump hegel-core version
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          NEW_VERSION: ${{ github.event.client_payload.version }}
          HEGEL_RELEASE_APP_ID: ${{ vars.HEGEL_RELEASE_APP_ID }}
        run: python .github/scripts/bump_hegel_core.py
