name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: test (${{ matrix.rust }})
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        rust: ["1.86", stable]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/base
        with:
          ssh-key: ${{ secrets.HEGEL_DEPLOY_KEY }}

      - uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@ad397744b0d591a723ab90405b7247fac0e6b8db # v2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.13"
      - name: Install hegel
        run: pip install "git+ssh://git@github.com/antithesishq/hegel.git"

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test
