name: Lint GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  zizmor:
    name: zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - name: Install zizmor
        run: pipx install zizmor
      - name: Run zizmor
        run: zizmor --format plain .github/
